/*
 * Copyright (c) 2026 Bastiaan van der Plaat
 *
 * SPDX-License-Identifier: MIT
 */

import {
    AccountIcon,
    AccountMultipleIcon,
    ArrowLeftIcon,
    ButtonCursorIcon,
    CardTextOutlineIcon,
    ClipboardTextOutlineIcon,
    CloseIcon,
    CloudUploadIcon,
    CodeBracesIcon,
    CodeTagsIcon,
    CogIcon,
    ContentSaveIcon,
    DeleteIcon,
    DeleteOutlineIcon,
    DownloadIcon,
    FormatBoldIcon,
    FormatItalicIcon,
    FormatLetterCaseIcon,
    FormatListBulletedIcon,
    FormatListNumberedIcon,
    FormatQuoteOpenIcon,
    FormatStrikethroughIcon,
    FormatUnderlineIcon,
    FormTextboxIcon,
    HistoryIcon,
    LaptopIcon,
    LinkIcon,
    LockIcon,
    LoginIcon,
    LogoutIcon,
    MagnifyIcon,
    MaterialDesignIcon,
    MessageTextOutlineIcon,
    MinusIcon,
    NoteTextIcon,
    PackageDownIcon,
    PackageUpIcon,
    PageLayoutHeaderIcon,
    PageLayoutSidebarLeftIcon,
    PaletteSwatchIcon,
    PencilIcon,
    PinIcon,
    PlusCircleIcon,
    PlusIcon,
    ProgressClockIcon,
    RestoreIcon,
    SecurityIcon,
    TableIcon,
    TagOutlineIcon,
    TextBoxIcon,
    TrayIcon,
    WeatherNightIcon,
    WeatherSunnyIcon,
} from 'plaatui';

// The showcase intentionally imports the complete catalog. Applications should
// import individual icon components directly so their bundler can tree-shake the rest.
export const iconCatalog = {
    account: AccountIcon,
    'account-multiple': AccountMultipleIcon,
    'arrow-left': ArrowLeftIcon,
    'button-cursor': ButtonCursorIcon,
    'card-text-outline': CardTextOutlineIcon,
    'clipboard-text-outline': ClipboardTextOutlineIcon,
    close: CloseIcon,
    'cloud-upload': CloudUploadIcon,
    'code-braces': CodeBracesIcon,
    'code-tags': CodeTagsIcon,
    cog: CogIcon,
    'content-save': ContentSaveIcon,
    delete: DeleteIcon,
    'delete-outline': DeleteOutlineIcon,
    download: DownloadIcon,
    'form-textbox': FormTextboxIcon,
    'format-bold': FormatBoldIcon,
    'format-italic': FormatItalicIcon,
    'format-letter-case': FormatLetterCaseIcon,
    'format-list-bulleted': FormatListBulletedIcon,
    'format-list-numbered': FormatListNumberedIcon,
    'format-quote-open': FormatQuoteOpenIcon,
    'format-strikethrough': FormatStrikethroughIcon,
    'format-underline': FormatUnderlineIcon,
    history: HistoryIcon,
    laptop: LaptopIcon,
    link: LinkIcon,
    lock: LockIcon,
    login: LoginIcon,
    logout: LogoutIcon,
    magnify: MagnifyIcon,
    'material-design': MaterialDesignIcon,
    'message-text-outline': MessageTextOutlineIcon,
    minus: MinusIcon,
    'note-text': NoteTextIcon,
    'package-down': PackageDownIcon,
    'package-up': PackageUpIcon,
    'page-layout-header': PageLayoutHeaderIcon,
    'page-layout-sidebar-left': PageLayoutSidebarLeftIcon,
    'palette-swatch': PaletteSwatchIcon,
    pencil: PencilIcon,
    pin: PinIcon,
    plus: PlusIcon,
    'plus-circle': PlusCircleIcon,
    'progress-clock': ProgressClockIcon,
    restore: RestoreIcon,
    security: SecurityIcon,
    table: TableIcon,
    'tag-outline': TagOutlineIcon,
    'text-box': TextBoxIcon,
    tray: TrayIcon,
    'weather-night': WeatherNightIcon,
    'weather-sunny': WeatherSunnyIcon,
} as const;

export type IconType = keyof typeof iconCatalog;
export const iconEntries = Object.entries(iconCatalog) as [IconType, (typeof iconCatalog)[IconType]][];
