[package]
name = "simple_logger"
version = "5.2.0+patch"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
jiff = "0.2.35"
log = { version = "0.4.34", features = ["std"] }

[target.'cfg(windows)'.dependencies]
enable-ansi-support = "0.3.1"
