[package]
name = "bob"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
basic-toml = "0.1.9"
dirs = "6.0"
dotenv = "0.15.0"
regex = { version = "1.11", default-features = false, features = [
    "unicode-perl",
] }
serde = { version = "1.0", features = ["derive"] }
sha1 = "0.10.6"
terminal_size = "0.4.2"
threadpool = "1.8"

[target.'cfg(windows)'.dependencies]
enable-ansi-support = "0.2.1"

[features]
default = ["javac-server"]
javac-server = []
