[package]
name = "bob"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
basic-toml = "0.1.9"
regex = { version = "1.11", default-features = false, features = [
    "unicode-perl",
] }
serde = { version = "1.0", features = ["derive"] }
threadpool = "1.8"
uuid = { version = "1.0", features = ["v4"] }
