/*
 * Copyright (c) 2024 Bastiaan van der Plaat
 *
 * SPDX-License-Identifier: MIT
 */

use indexmap::IndexMap;

use crate::openapi::Schema;
use crate::utils::ToCapitalize;

pub(crate) fn generate_schemas(schemas: IndexMap<String, Schema>, output_path: &str) {
    let mut code_schemas = IndexMap::new();

    // Generate code for schemas
    for (name, schema) in schemas {
        schema_generate_code(&mut code_schemas, name.clone(), &schema, false);
    }

    // Write .rs file
    let mut code = "// This file is generated by openapi-generator, do not edit!\n\n".to_string();
    for code_schema in code_schemas.values() {
        code.push_str(code_schema);
    }
    std::fs::write(output_path, code)
        .unwrap_or_else(|_| panic!("Failed to write: {}", output_path));
}

fn schema_generate_code(
    code_schemas: &mut IndexMap<String, String>,
    name: String,
    schema: &Schema,
    is_optional: bool,
) -> String {
    if let Some(r#ref) = &schema.r#ref {
        let ref_parts: Vec<&str> = r#ref.split('/').collect();
        let ref_name = ref_parts.last().expect("Invalid ref");
        if name == *ref_name {
            return format!("Box<{}>", ref_name);
        }
        return ref_name.to_string();
    }

    if let Some(r#enum) = &schema.r#enum {
        let name = name.to_capitalize();
        let mut code = String::new();
        code.push_str(&format!("#[derive(Copy, Clone, Eq, PartialEq, serde::Deserialize, serde::Serialize)]\npub(crate) enum {} {{\n", name));
        for variant in r#enum {
            code.push_str(&format!(
                "    #[serde(rename = \"{}\")]\n    {},\n",
                variant,
                variant.to_capitalize()
            ));
        }
        code.push_str("}\n\n");
        code_schemas.insert(name.clone(), code);
        return name;
    }

    if let Some(additional_properties) = &schema.additional_properties {
        let field_type =
            schema_generate_code(code_schemas, name.clone(), additional_properties, false);
        let code = format!(
            "#[derive(Clone, serde::Deserialize, serde::Serialize)]\npub(crate) struct {}(std::collections::HashMap<String, {}>);\n\n",
            name,
            field_type
        );
        code_schemas.insert(name.clone(), code);
        return name;
    }

    let r#type = schema.r#type.as_ref().expect("Schema should have type");
    if r#type == "object" {
        let mut code = String::new();
        code.push_str(&format!(
            "#[derive(Clone, serde::Deserialize, serde::Serialize)]\npub(crate) struct {} {{\n",
            name
        ));
        if let Some(properties) = &schema.properties {
            for (prop_name, prop_schema) in properties {
                let prop_type = schema_generate_code(
                    code_schemas,
                    prop_name.to_string(),
                    prop_schema,
                    schema
                        .required
                        .as_ref()
                        .map(|required| !required.contains(prop_name))
                        .unwrap_or_else(|| true),
                );
                let prop_name = prop_name.replace("type", "r#type");
                code.push_str(&format!("    pub {}: {},\n", prop_name, prop_type));
            }
        }
        code.push_str("}\n\n");
        code_schemas.insert(name.clone(), code);
        return name;
    }

    let r#type = match r#type.as_str() {
        "string" => {
            if schema.r#enum.is_some() {
                return schema_generate_code(code_schemas, name, schema, false);
            }
            match schema.format.as_deref() {
                Some("uuid") => "uuid::Uuid",
                Some("date-time") => "chrono::DateTime<chrono::Utc>",
                _ => "String",
            }
            .to_string()
        }
        "number" => match schema.format.as_deref() {
            Some("float") => "f32",
            _ => "f64",
        }
        .to_string(),
        "integer" => match schema.format.as_deref() {
            Some("int32") => "i32",
            _ => "i64",
        }
        .to_string(),
        "boolean" => "bool".to_string(),
        "array" => {
            let items = schema.items.as_ref().expect("No items");
            let item_type = schema_generate_code(code_schemas, "item".to_string(), items, false);
            format!("Vec<{}>", item_type)
        }
        _ => panic!("Unsupported type"),
    };
    if is_optional {
        format!("Option<{}>", r#type)
    } else {
        r#type
    }
}
