[package]
name = "bwebview"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
directories = { version = "6.0", optional = true }
mime_guess = { version = "2.0", default-features = false, optional = true }
log = { version = "0.4.34", optional = true }
rust-embed = { version = "8.12", optional = true }
small-http = { version = "0.2.1", optional = true, default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
block2 = "0.6.2"
objc2 = "0.6.4"

# The WebView2 user data folder always needs a config directory on Windows
[target.'cfg(windows)'.dependencies]
directories = "6.0"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
winresource = "0.1.31"

[features]
default = ["log", "remember_window_state"]
custom_protocol = ["dep:small-http"]
dialog = []
file_drop = []
log = ["dep:log"]
menu = []
progress_bar = []
remember_window_state = ["dep:directories"]
rust-embed = ["custom_protocol", "dep:rust-embed", "dep:mime_guess"]

[[example]]
name = "bwebview-dialog"
required-features = ["dialog"]

[[example]]
name = "bwebview-file-drop"
required-features = ["file_drop"]

[[example]]
name = "bwebview-ipc"
required-features = ["remember_window_state"]

[[example]]
name = "bwebview-menu"
required-features = ["menu"]

[[example]]
name = "bwebview-progress-bar"
required-features = ["progress_bar"]
