[package]
name = "bwebview"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bwindow = { path = "../bwindow", default-features = false }
mime_guess = { version = "2.0", default-features = false, optional = true }
log = { version = "0.4.34", optional = true }
rust-embed = { version = "8.12", optional = true }
small-http = { version = "0.2.1", optional = true, default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
block2 = "0.6.2"
objc2 = "0.6.4"

[dev-dependencies]
bcanvas = { path = "../bcanvas" }
bwindow = { path = "../bwindow", features = ["dialog", "file_drop", "menu", "progress_bar"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
winresource = "0.1.31"

[features]
default = ["log"]
custom_protocol = ["dep:small-http"]
file_drop = ["bwindow/file_drop"]
log = ["dep:log"]
rust-embed = ["custom_protocol", "dep:rust-embed", "dep:mime_guess"]

[[example]]
name = "bwebview-dialog"

[[example]]
name = "bwebview-file-drop"
required-features = ["file_drop"]

[[example]]
name = "bwebview-ipc"

[[example]]
name = "bwebview-menu"

[[example]]
name = "bwebview-progress-bar"
