[package]
name = "manexplorer"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[package.metadata.bundle]
name = "ManExplorer"
identifier = "nl.bplaat.ManExplorer"
copyright = "Copyright © 2025 Bastiaan van der Plaat"
iconset = "meta/macos/icon.iconset"

[lints]
workspace = true

[dependencies]
bwebview = { path = "../../lib/bwebview", features = ["rust-embed"] }

rust-embed = "8.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
small-http = { version = "0.2.0", default-features = false, features = [
    "json",
] }
