[package]
name = "webhook-puller"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
ini = { path = "../../lib/ini" }
log = "0.4.28"
simple_logger = "5.0.0"
small-http = { version = "0.2.0", features = ["json"] }
