[package]
name = "webhook-puller"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
small-http = { version = "0.1.0", features = ["json"] }

serde = { version = "1.0", features = ["derive"] }
serde_urlencoded = "0.7.1"
serde_yaml = "0.9.34"
