[package]
name = "webhook-puller"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
small-http = { version = "0.2.0", features = ["json"] }

basic-toml = "0.1.9"
serde = { version = "1.0", features = ["derive"] }
serde_urlencoded = "0.7.1"
