[package]
name = "jubicamp-timemachine"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
tiny-webview = { path = "../../lib/tiny-webview", features = ["rust-embed"] }

rust-embed = "8.7"
