[package]
name = "cargo-bundle"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
basic-toml = "0.1.9"
serde = { version = "1.0", features = ["derive"] }
