[package]
name = "hmac"
version = "0.13.0+patch"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
digest = "0.11.3"

[dev-dependencies]
criterion = { path = "../criterion" }
sha2 = "0.11.0"

[[bench]]
name = "hmac"
harness = false
