[package]
name = "small-router"
version = "0.2.1"
edition = "2021"
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1.0"
log = { version = "0.4.34", optional = true }
small-http = { version = "0.2.1", default-features = false }

[features]
log = ["dep:log"]
