[package]
name = "bassielight"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
rusb = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tiny-webview = { path = "../../lib/tiny-webview" }

[build-dependencies]
minify-html = { path = "../../lib/minify-html" }
