[package]
name = "bassielight"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[package.metadata.bundle]
name = "BassieLight"
identifier = "nl.bplaat.BassieLight"
copyright = "Copyright © 2025 Bastiaan van der Plaat"
iconset = "meta/macos/icon.iconset"

[lints]
workspace = true

[dependencies]
bwebview = { path = "../../lib/bwebview", features = ["rust-embed"] }
dirs = "6.0.0"
rusb = { version = "0.9", features = ["vendored"] }
rust-embed = { version = "8.7", features = ["interpolate-folder-path"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
small-http = { version = "0.2.0", default-features = false }
small-websocket = { path = "../../lib/small-websocket", default-features = false }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"
