[package]
name = "XStreaks"
id = "nl.plaatsoft.XStreaks"
version = "0.1.0"

[dependencies]
cocoa = { framework = "Cocoa" }

[package.metadata.bundle]
icon = "icons/icon.icon"
resources_dir = "res"
copyright = "Copyright © 2025-2026 Bastiaan van der Plaat"
