[package]
name = "XStreaks"
id = "nl.plaatsoft.XStreaks"
version = "0.1.0"

[dependencies]
cocoa = { framework = "Cocoa" }

[package.metadata.bundle]
lipo = true
icon = "icons/icon.icon"
copyright = "Copyright © 2025 Bastiaan van der Plaat"
