[package]
name = "Alert"
id = "com.example.Alert"
version = "0.1.0"

[dependencies]
cocoa = { framework = "Cocoa" }

[package.metadata.bundle]
iconset = "icons/icon.iconset"
resources_dir = "res"
copyright = "Copyright © 2025 Bastiaan van der Plaat"
