# Enable stricter unsafe code guidelines
[build]
rustflags = ["-Dunsafe_op_in_unsafe_fn"]

# Enable optimizations for release builds for smaller binaries
[profile.release]
strip = true
opt-level = "z"
lto = "thin"
panic = "abort"
overflow-checks = false
