[package]
name = "plaatnotes"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bsqlite = { version = "0.1.2", features = ["uuid", "chrono", "bundled"] }
chrono = { version = "0.4", default-features = false, features = [
    "now",
    "serde",
] }
const_format = "0.2"
log = "0.4.28"
mime_guess = { version = "2.0", default-features = false }
rust-embed = { version = "8.7", features = ["interpolate-folder-path"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7.1"
simple_logger = "5.0.0"
small-http = { version = "0.2.0", features = ["json"] }
small-router = "0.2.0"
uuid = { version = "1.0", features = ["v7", "serde"] }
validate = { path = "../../lib/validate", features = ["serde"] }

[build-dependencies]
openapi-generator = { path = "../../lib/openapi-generator" }
copy_dir = "0.1.3"
