services:
  plaatnotes:
    image: ghcr.io/bplaat/plaatnotes:latest
    container_name: plaatnotes
    restart: unless-stopped
    environment:
      SERVER_PORT: 8080
      DATABASE_PATH: 'data/database.db'
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: Password123!
    ports:
      - '8080:8080'
    volumes:
      - ./data/:/app/data/
