[package]
name = "vector"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = ["svg", "tinyvg"]
svg = ["dep:xmlparser"]
tinyvg = []

[dependencies]
xmlparser = { version = "0.13.6", optional = true }

[dev-dependencies]
criterion = { path = "../criterion" }
image = { path = "../image", default-features = false, features = ["png"] }

[[bench]]
name = "vector"
harness = false
