[package]
name = "example-simple"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
http = { path = "../../lib/http" }

serde = { version = "1.0", features = ["derive"] }
serde_urlencoded = "0.7.1"
