[package]
name = "rust-embed-impl"
version = "8.12.0+patch"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = "3.0"

[features]
interpolate-folder-path = []

[dev-dependencies]
trybuild = "1.0"
