[package]
name = "zeroize"
version = "1.9.0+patch"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Minimal patched replacement for securely zeroing memory"

[lints]
workspace = true

[dependencies]
serde = { version = "1.0", optional = true }

[features]
serde = ["dep:serde"]
aarch64 = []
simd = []
