name: build-deploy

on:
  workflow_run:
    workflows: ['check']
    branches: [master]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-deploy-pages:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Install extra Rust tooling
        run: |
          rustup target add wasm32-unknown-unknown
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall -y wasm-bindgen-cli --version 0.2.104
      - name: Build pages
        run: ./meta.sh build-pages
      - name: Upload pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './target/pages'
      - id: deployment
        name: Deploy pages
        uses: actions/deploy-pages@v4
